### ISSUE TITLE
Spacebar crash due to debug combat screen

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#150]
## Description
Spacebar opens a debug combat screen with no enemy and will crash the game on close sometimes will crash on open.

## How To Reproduce
Start the game
Press space

## Expected Behaviour
Space should ideally do nothing in the current game but it is used for a test quest.

**Comment by owenrharding** [comment]
Hey Noah, am I right in my understanding that the `attack()` function in `PlayerActions' is completely not needed? Am I right to go ahead and remove it?

**Comment by callumreillyy** [comment]
in pull request #149 (commit 19bd33e91a838472727d44582cae8579b5f8ef28) changes are made to the saves file (can be seen at following link https://github.com/UQcsse3200/2024-studio-2/commit/19bd33e91a838472727d44582cae8579b5f8ef28) I believe this was the bug relating to space bar crashing the game. Essentially quests were being triggered within the json and it was bugging quest 2 was a trigger for spawning the boss. 

Not sure about the stats being invisible still searching through the enemy main commit.

**Comment by callumreillyy** [comment]
Ok so it definitely related to the WanderTask class which in commit #149 includes some directional wandering for frog and chicken. After removing this the 'space crash bug' is gone. Stat combat screen bug persists. After reverting class back to code from commit #147 the wander animations for frog and chicken remain which is interesting.
