### ISSUE TITLE
Items not showing at the start of the game

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#159]
## Description
Items (apples, potions) not showing at the start of the game

## How To Reproduce
Steps to reproduce the behaviour:
1. Start the game
2. See item not showing

## Expected Behaviour
Item should be spawned around the map

**Comment by mitsudz** [comment]
This is not a bug - the items are just currently being spawned randomly and only a few of them are spawned. I will be working on integrating their spawning with chunk generation. If you wish to see the items temporarily just spawn a few at static locations close to the center of the map. See branch connected to issue #164 for details.
