### ISSUE TITLE
Items picked up when Inventory is full

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#252]
## Description
Even after the inventory is filled up, pressing P removes items from the ground.

## How To Reproduce
Steps to reproduce the behaviour:
Start the game and pick up items until the inventory is full. Attempt to pick up further items.

## Expected Behaviour
Either nothing happens and the items are left on the ground, or some sort of pop up text appears and then fades informing the user that the inventory is full.

**Comment by lhick2108** [comment]
Solved bug by adding check to see if inventory is full.
Solved in this pr, Merge pull request #265
