### ISSUE TITLE
BUG: Game Crashing When Projectile Hits Tree!

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#428]
## Description
The game crashes if a banana (from a monkey throw) comes into contact with a tree. This is because the target (the tree) has no combat stats component and so a null pointer is returned when attempting to get it as this is not accounted for. Dereferencing this null pointer leads to the game crashing.

## How To Reproduce
1. Go to the entitySpawn.json config file
2. Set all values to 0.
3. Set NUM_MONKEYS to 20 (or some other similarly high value)
4. Set NUM_TREES to 30 (or some similarly high value)
5. Play the game, and try to get monkeys to throw bananas at you. 
6. Attempt to move in such a way that the projectile will hit a tree that is between you and the monkey.
7. Observe the game crashing:(

## Expected Behaviour
The game should not crash, in fact the projectiles should have no influence on any non-player object (ie hitting another monkey should not incur friendly fire - if this isn't what we want this is a design decision that can be made later).

## Screenshots
<img width="1300" alt="Screenshot 2024-09-29 at 12 57 52 PM" src="https://github.com/user-attachments/assets/9abf719b-012a-4225-9b3b-d1609e27e90d">
<img width="1169" alt="Screenshot 2024-09-29 at 12 58 02 PM" src="https://github.com/user-attachments/assets/4208f2de-1e39-4d5a-ad21-61805fab8167">

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
