### ISSUE TITLE
Resizing after Start

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#587]
## Description
The minimise and maximise button causes screen resizing issues after the 'animal selection screen'. This issue is acute by the system maximise and minimise buttons being used.

## How To Reproduce
Steps to reproduce the behaviour:
1. Minimise using custom minimise button
2. Maximise using system maximise button
3. Continue through steps to start game
4. See screen resize without command

## Expected Behaviour
The screens should not resize without the user applying those resizing method.

## Temporary Fix
Not detrimental to game can be played and tested regardless of issue.

**Comment by jt-09** [comment]
done in PR #589
