### ISSUE TITLE
Night Mode Lag

### ISSUE THREAD

**Issue by TarushiG** [UQcsse3200/2024-studio-2#650]
## Description
There's a lag in the main menu's transition from night to day mode.

## How To Reproduce
Steps to reproduce the behaviour:
1. Go to 'main menu'
2. Click on 'night mode' top left button
3. You don't need to scroll

## Expected Behaviour
There should be no lag.

## Temporary Fix
Texture loading.

**Comment by jt-09** [comment]
fixed in pr #653
