### ISSUE TITLE
[Team 9] End Game (Final Boss)

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#9]
# **Description**

This feature will encompass the end of the first zone of the game, including the final boss, a trigger for the boss to appear and the screens/flow of the game once the boss encounter is completed, either in victory or defeat. The boss will appear on a trigger to be defined by the story/design committee and after some dialogue combat will begin. On combat ending the game will transfer to a new screen with a summary of the game showing victory or defeat. The game will then return to the main menu. 

## SubFeature/component (optional)
-The final Boss - actions/behaviour
-Trigger for game end phase - spawn of the boss (and possible minions)
-Dialogue/pre fight actions
-Summary/Game over screen

# **Dependencies**
Main dependencies, but all other features will be involved.
- Player - Team 1 (#4)
- Enemies - Team 2 (#11)
- Combat - Team 10 (#7)
- Map - Team 8 (#8)
- Progression - Team 5 (#13)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #53 (25 Aug)
- [x] #51 (25 Aug)
- [x] #52 (25 Aug)
- [x] #50 (27 Aug)
- [x] Documentation and Testing (29 Aug)

**Completion Deadline:** Aug. 29

# **Documentation**
- [Final Boss Sprite](../wiki/Final-Boss/Zone1-Final-Boss(ECS))
- [Boss Trigger](../wiki/Final-Boss/Zone1-Boss-Trigger)
- [Final Boss win / lose event](../wiki/Final-Boss/Zone1-Boss-Win-Lose)

# **Members**
- Phurin Vanasrivilai (phurinjeffy)
- Jose Leoncio (reonse)
- Callum Reilly (callumreillyy
- Joseph Thorne (joe-thorne)
- Ajay Datt (Ajay-Datt)

**Comment by joe-thorne** [comment]
Closed with acceptance of Pull Request #147
